apiVersion: v1
kind: Namespace
metadata:
  name: hello-staging
  labels:
    environment-id: env_64492151-ec89-4c93-a51b-d2ec840ffdef
    project-id: project_3ebb3db3-aab3-4e81-968d-7eb08c883dcf
    project-name: Hello
    environment-name: staging
    organization-id: org_3fab25b8-aa43-483a-b9bb-edd795459063
